[server]
headless = true
port = 8501
address = "0.0.0.0"
enableCORS = false

fileWatcherType = "auto"
runOnSave = true

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = true

[theme]
primaryColor = "#4CAF50"             # Verde suave moderno
backgroundColor = "#FFFFFF"          # Fundo branco clean
secondaryBackgroundColor = "#F5F7FA" # Cinza muito claro, quase branco
textColor = "#2C3E50"                # Cinza-azulado elegante
font = "sans serif"                  # Fonte moderna e clean
